[project]
name = "ff-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "asttokens>=3.0.0",
    "ipykernel>=6.30.1",
    "lxml>=6.0.2",
    "pandas>=2.3.2",
    "playwright>=1.55.0",
    "streamlit>=1.50.0",
]
